import "@/public/style/globals.css";
import "@/public/style/style.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-svh bg-neutral-100">
        <main className="w-full grow">{children}</main>
      </body>
    </html>
  );
}
